import os
import uuid
import json
import re
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

AUDIT_LOG_FILE = "audit_log.jsonl"


def llm_signal(text):
    prompt = (
        "You are an AI-generated text detector. Analyze the following text and determine "
        "whether it was likely written by AI or a human.\n\n"
        "Return ONLY valid JSON with these fields:\n"
        '- "attribution": one of "likely_ai", "likely_human", or "uncertain"\n'
        '- "llm_score": a float between 0.0 (confident human) and 1.0 (confident AI)\n'
        '- "short_explanation": a brief explanation (include this when confidence is low)\n\n'
        f"Text to analyze:\n\"{text}\""
    )

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    json_match = re.search(r'\{.*\}', raw, re.DOTALL)
    if json_match:
        raw = json_match.group(0)

    result = json.loads(raw)

    return {
        "attribution": result.get("attribution", "uncertain"),
        "llm_score": float(result.get("llm_score", 0.5)),
    }


def write_audit_entry(entry):
    with open(AUDIT_LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")


def read_audit_log(limit=50):
    if not os.path.exists(AUDIT_LOG_FILE):
        return []
    with open(AUDIT_LOG_FILE, "r") as f:
        entries = [json.loads(line) for line in f if line.strip()]
    return entries[-limit:]


@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json()
    if not data or "text" not in data:
        return jsonify({"error": "Missing 'text' field"}), 400

    text = data["text"]
    creator_id = data.get("creator_id", "anonymous")
    content_id = str(uuid.uuid4())

    signal_result = llm_signal(text)

    confidence = signal_result["llm_score"]
    attribution = signal_result["attribution"]

    if confidence >= 0.75:
        label = ("High-confidence AI: Our system has high confidence this piece was "
                 "generated by AI. If you believe this is incorrect, you may submit "
                 "an appeal for human review.")
    elif confidence >= 0.40:
        label = ("Uncertain: The system could not confidently determine whether this "
                 "was written by AI or a human. A human review may help resolve this.")
    else:
        label = ("High-confidence human: Our system has high confidence this piece was "
                 "written by a human. If you believe this is incorrect, you may still appeal.")

    audit_entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "signal_outputs": {"llm": signal_result},
        "label": label,
        "status": "classified",
    }
    write_audit_entry(audit_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_audit_log()
    return jsonify({"entries": entries})


if __name__ == "__main__":
    app.run(debug=True, port=5001)
