import os
import uuid
import json
import re
import statistics
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

AUDIT_LOG_FILE = "audit_log.jsonl"


def llm_signal(text):
    prompt = (
        "You are an AI-generated text detector. Analyze the following text and determine "
        "whether it was likely written by AI or a human.\n\n"
        "Return ONLY valid JSON with these fields:\n"
        '- "attribution": one of "likely_ai", "likely_human", or "uncertain"\n'
        '- "llm_score": a float between 0.0 (confident human) and 1.0 (confident AI)\n'
        '- "short_explanation": a brief explanation (include this when confidence is low)\n\n'
        f"Text to analyze:\n\"{text}\""
    )

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    json_match = re.search(r'\{.*\}', raw, re.DOTALL)
    if json_match:
        raw = json_match.group(0)

    result = json.loads(raw)

    return {
        "attribution": result.get("attribution", "uncertain"),
        "llm_score": float(result.get("llm_score", 0.5)),
    }


def stylometric_signal(text):
    sentences = [s for s in re.split(r'(?<=[.!?])\s+', text.strip()) if s.strip()]
    words = re.findall(r"\b[a-zA-Z']+\b", text.lower())

    if not words or not sentences:
        return {
            "stylometric_score": 0.5,
            "metrics": {
                "avg_sentence_length": 0,
                "sentence_length_variance": 0,
                "type_token_ratio": 0,
                "punctuation_density": 0,
            },
        }

    sentence_lengths = [len(re.findall(r"\b[a-zA-Z']+\b", s)) for s in sentences]
    avg_sentence_length = statistics.mean(sentence_lengths)
    sentence_length_variance = statistics.pvariance(sentence_lengths) if len(sentence_lengths) > 1 else 0

    type_token_ratio = len(set(words)) / len(words)
    punctuation_density = sum(1 for c in text if c in ',;:—-') / len(text)

    # low sentence length variance (uniform sentences) reads as more AI-like.
    variance_score = 1 / (1 + sentence_length_variance / 20)
    # ai text tends to favor longer amd more formal sentences.
    length_score = min(avg_sentence_length / 25, 1.0)
    # a narrower vocabulary (lower type token ratio) reads as more ai like.
    ttr_score = 1 - min(type_token_ratio, 1.0)

    stylometric_score = (0.4 * variance_score) + (0.3 * length_score) + (0.3 * ttr_score)
    stylometric_score = max(0.0, min(1.0, stylometric_score))

    return {
        "stylometric_score": round(stylometric_score, 3),
        "metrics": {
            "avg_sentence_length": round(avg_sentence_length, 2),
            "sentence_length_variance": round(sentence_length_variance, 2),
            "type_token_ratio": round(type_token_ratio, 3),
            "punctuation_density": round(punctuation_density, 3),
        },
    }


def combine_scores(llm_output, stylometric_output, w_llm=0.7, w_stylo=0.3):
    confidence = (w_llm * llm_output["llm_score"]) + (w_stylo * stylometric_output["stylometric_score"])
    return round(max(0.0, min(1.0, confidence)), 3)


def classify_confidence(confidence):
    if confidence >= 0.75:
        return "likely_ai", (
            "High-confidence AI: Our system has high confidence this piece was "
            "generated by AI. If you believe this is incorrect, you may submit "
            "an appeal for human review."
        )
    elif confidence >= 0.40:
        return "uncertain", (
            "Uncertain: The system could not confidently determine whether this "
            "was written by AI or a human. A human review may help resolve this."
        )
    else:
        return "likely_human", (
            "High-confidence human: Our system has high confidence this piece was "
            "written by a human. If you believe this is incorrect, you may still appeal."
        )


def write_audit_entry(entry):
    with open(AUDIT_LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")


def read_audit_log(limit=50):
    if not os.path.exists(AUDIT_LOG_FILE):
        return []
    with open(AUDIT_LOG_FILE, "r") as f:
        entries = [json.loads(line) for line in f if line.strip()]
    return entries[-limit:]


@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json()
    if not data or "text" not in data:
        return jsonify({"error": "Missing 'text' field"}), 400

    text = data["text"]
    creator_id = data.get("creator_id", "anonymous")
    content_id = str(uuid.uuid4())

    llm_result = llm_signal(text)
    stylometric_result = stylometric_signal(text)
    confidence = combine_scores(llm_result, stylometric_result)

    attribution, label = classify_confidence(confidence)

    audit_entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "signal_outputs": {"llm": llm_result, "stylometric": stylometric_result},
        "label": label,
        "status": "classified",
    }
    write_audit_entry(audit_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_audit_log()
    return jsonify({"entries": entries})


if __name__ == "__main__":
    app.run(debug=True, port=5001)
